### ISSUE TITLE
cant get the backend to run and communicate with metamask

### ISSUE THREAD

**Issue by SECRYPT-2022** [chainflag/eth-faucet#23]
I have the web front end running with

`cd /path to/eth-faucet/web/`

`nohup npm start &`

but cant appear to get the backend communicating with my testnet to send test coins on the faucet.

I have followed the go generate

`cd ~/eth-faucet`

`go build -o eth-faucet`

unsure how to do the usage and config part of it.

**Comment by iczc** [comment]
This project utilizes the "go embed" feature to consolidate frontend static files directly into the Go binary, thus eliminating the need to run the frontend and backend as separate entities.

Here's the correct procedure for usage:
1. Build frontend using `npm run build` or `go generate`
2. Build go binary that incorporates frontend static files using `go build -o eth-faucet`
3. Execute the binary program with command-line flags and subsequently navigate to http://127.0.0.1:8080

**Comment by SECRYPT-2022** [comment]
i dont need to configure anything or fund a wallet so who ever request test tokens can receive?

**Comment by iczc** [comment]
> i dont need to configure anything or fund a wallet so who ever request test tokens can receive?

You need to configure the wallet private key or keystore via command line arguments, please see readme: https://github.com/chainflag/eth-faucet#usage

**Comment by SECRYPT-2022** [comment]
my intial question was that i am unsure how to configure the wallet private key or keystore via the commands.

is there any chance you could assist?

**Comment by iczc** [comment]
`./eth-faucet -httpport 8080 -wallet.provider <your provider> -wallet.privkey <your private key>`
